//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:31:51 PM GMT 
//


package org.nmrml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AtomAssingmentAnnotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AtomAssingmentAnnotationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chemicalCompound" type="{http://nmrml.org/schema}ChemicalCompoundType"/>
 *         &lt;element name="atomAssignmentList" type="{http://nmrml.org/schema}AtomAssignmentListType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="spectrumRef" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AtomAssingmentAnnotationType", propOrder = {
    "chemicalCompound",
    "atomAssignmentList"
})
public class AtomAssingmentAnnotationType {

    @XmlElement(required = true)
    protected ChemicalCompoundType chemicalCompound;
    protected AtomAssignmentListType atomAssignmentList;
    @XmlAttribute(name = "spectrumRef", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object spectrumRef;

    /**
     * Gets the value of the chemicalCompound property.
     * 
     * @return
     *     possible object is
     *     {@link ChemicalCompoundType }
     *     
     */
    public ChemicalCompoundType getChemicalCompound() {
        return chemicalCompound;
    }

    /**
     * Sets the value of the chemicalCompound property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChemicalCompoundType }
     *     
     */
    public void setChemicalCompound(ChemicalCompoundType value) {
        this.chemicalCompound = value;
    }

    /**
     * Gets the value of the atomAssignmentList property.
     * 
     * @return
     *     possible object is
     *     {@link AtomAssignmentListType }
     *     
     */
    public AtomAssignmentListType getAtomAssignmentList() {
        return atomAssignmentList;
    }

    /**
     * Sets the value of the atomAssignmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtomAssignmentListType }
     *     
     */
    public void setAtomAssignmentList(AtomAssignmentListType value) {
        this.atomAssignmentList = value;
    }

    /**
     * Gets the value of the spectrumRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getSpectrumRef() {
        return spectrumRef;
    }

    /**
     * Sets the value of the spectrumRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setSpectrumRef(Object value) {
        this.spectrumRef = value;
    }

}
