//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:31:51 PM GMT 
//


package org.nmrml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChemicalCompoundType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChemicalCompoundType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifierList" type="{http://nmrml.org/schema}CompoundIdentifierListType" minOccurs="0"/>
 *         &lt;element name="structure" type="{http://nmrml.org/schema}CompoundStructureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChemicalCompoundType", propOrder = {
    "identifierList",
    "structure"
})
@XmlSeeAlso({
    QuantifiedCompoundType.class
})
public class ChemicalCompoundType {

    protected CompoundIdentifierListType identifierList;
    protected CompoundStructureType structure;
    @XmlAttribute(name = "name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the identifierList property.
     * 
     * @return
     *     possible object is
     *     {@link CompoundIdentifierListType }
     *     
     */
    public CompoundIdentifierListType getIdentifierList() {
        return identifierList;
    }

    /**
     * Sets the value of the identifierList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompoundIdentifierListType }
     *     
     */
    public void setIdentifierList(CompoundIdentifierListType value) {
        this.identifierList = value;
    }

    /**
     * Gets the value of the structure property.
     * 
     * @return
     *     possible object is
     *     {@link CompoundStructureType }
     *     
     */
    public CompoundStructureType getStructure() {
        return structure;
    }

    /**
     * Sets the value of the structure property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompoundStructureType }
     *     
     */
    public void setStructure(CompoundStructureType value) {
        this.structure = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
