//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:31:51 PM GMT 
//


package org.nmrml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompoundStructureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompoundStructureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="atomList" type="{http://nmrml.org/schema}AtomListType"/>
 *         &lt;element name="bondList" type="{http://nmrml.org/schema}BondListType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompoundStructureType", propOrder = {
    "atomList",
    "bondList"
})
public class CompoundStructureType {

    @XmlElement(required = true)
    protected AtomListType atomList;
    @XmlElement(required = true)
    protected BondListType bondList;

    /**
     * Gets the value of the atomList property.
     * 
     * @return
     *     possible object is
     *     {@link AtomListType }
     *     
     */
    public AtomListType getAtomList() {
        return atomList;
    }

    /**
     * Sets the value of the atomList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtomListType }
     *     
     */
    public void setAtomList(AtomListType value) {
        this.atomList = value;
    }

    /**
     * Gets the value of the bondList property.
     * 
     * @return
     *     possible object is
     *     {@link BondListType }
     *     
     */
    public BondListType getBondList() {
        return bondList;
    }

    /**
     * Sets the value of the bondList property.
     * 
     * @param value
     *     allowed object is
     *     {@link BondListType }
     *     
     */
    public void setBondList(BondListType value) {
        this.bondList = value;
    }

}
