//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:31:51 PM GMT 
//


package org.nmrml.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Caputures information about analytes that have been quantified in a mixture. The infromation is about quantification and identification of the analytes.
 * 
 * <p>Java class for QuantifiedCompoundListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuantifiedCompoundListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="quantifiedCompound" type="{http://nmrml.org/schema}QuantifiedCompoundType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuantifiedCompoundListType", propOrder = {
    "quantifiedCompound"
})
public class QuantifiedCompoundListType {

    @XmlElement(required = true)
    protected List<QuantifiedCompoundType> quantifiedCompound;

    /**
     * Gets the value of the quantifiedCompound property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the quantifiedCompound property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuantifiedCompound().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuantifiedCompoundType }
     * 
     * 
     */
    public List<QuantifiedCompoundType> getQuantifiedCompound() {
        if (quantifiedCompound == null) {
            quantifiedCompound = new ArrayList<QuantifiedCompoundType>();
        }
        return this.quantifiedCompound;
    }

}
