//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:31:51 PM GMT 
//


package org.nmrml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Spectrum1DType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Spectrum1DType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://nmrml.org/schema}SpectrumType">
 *       &lt;sequence>
 *         &lt;element name="firstDimensionProcessingParameterSet" type="{http://nmrml.org/schema}FirstDimensionProcessingParameterSetType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Spectrum1DType", propOrder = {
    "firstDimensionProcessingParameterSet"
})
public class Spectrum1DType
    extends SpectrumType
{

    protected FirstDimensionProcessingParameterSetType firstDimensionProcessingParameterSet;

    /**
     * Gets the value of the firstDimensionProcessingParameterSet property.
     * 
     * @return
     *     possible object is
     *     {@link FirstDimensionProcessingParameterSetType }
     *     
     */
    public FirstDimensionProcessingParameterSetType getFirstDimensionProcessingParameterSet() {
        return firstDimensionProcessingParameterSet;
    }

    /**
     * Sets the value of the firstDimensionProcessingParameterSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link FirstDimensionProcessingParameterSetType }
     *     
     */
    public void setFirstDimensionProcessingParameterSet(FirstDimensionProcessingParameterSetType value) {
        this.firstDimensionProcessingParameterSet = value;
    }

}
