
import java.io.FileInputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.GregorianCalendar;

import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import javax.xml.bind.*;

// import java content classes generated by binding compiler
import org.nmrml.schema.*;

/*
 * $Id: dx2nmrML.java,v 1.1 2013-07-15 09:49:33 DJ $
 */
 
public class dx2nmrML {
    
    // This sample application demonstrates how to create a nmrML file
    // based on a java content tree generated by the JAXB XJC Tool (JDK 7 and above).

    public static void main( String[] args ) {

        try {

            ObjectFactory objFactory = new ObjectFactory();
            NmrMLType nmrMLtype = (NmrMLType) objFactory.createNmrMLType();
 
            nmrMLtype.setVersion("1.0");
            nmrMLtype.setAccession("S1");

       /* CV List : used as references for all CV in the document */
            CVListType cvList = (CVListType) objFactory.createCVListType();
            CVType cvNMR = (CVType) objFactory.createCVType();
            cvNMR.setId("NMR");
            cvNMR.setFullName("Nuclear Magnetic Resonance CV");
            cvNMR.setVersion("0.1.0");
            cvNMR.setURI("http://msi-ontology.sourceforge.net/ontology/NMR.owl");
            cvList.getCv().add(cvNMR);
            CVType cvOBI = (CVType) objFactory.createCVType();
            cvOBI.setId("OBI");
            cvOBI.setFullName("Ontology for Biomedical Investigations");
            cvOBI.setVersion("2012.07.01");
            cvOBI.setURI("http://purl.obolibrary.org/obo/obi");
            cvList.getCv().add(cvOBI);
            CVType cvUO = (CVType) objFactory.createCVType();
            cvUO.setId("UO");
            cvUO.setFullName("Unit Ontology");
            cvUO.setVersion("3.2.0");
            cvUO.setURI("http://purl.obolibrary.org/obo/");
            cvList.getCv().add(cvUO);
            cvList.setCount(new BigInteger("3"));
            nmrMLtype.setCvList(cvList);


       /* FileDescription */
            FileDescriptionType filedesc = (FileDescriptionType) objFactory.createFileDescriptionType();
            ParamGroupType paramgrp = (ParamGroupType) objFactory.createParamGroupType();
            CVParamType cvp1 = (CVParamType) objFactory.createCVParamType();
            String cvref="NMR";
            cvp1.setCvRef(cvNMR);
            cvp1.setAccession("#NMR_400128");
            cvp1.setName("NMR Sample");
            cvp1.setValue("");
            paramgrp.getCvParam().add(cvp1);
            filedesc.setFileContent(paramgrp);
            nmrMLtype.setFileDescription(filedesc);

       /* Contact List */
       /* SourceFile List */
       /* Software List */
       /* InstrumentConfiguration List */
       /* DataProcessing List */
       /* Sample List */
       /* ReferenceableParamGroup List */
       /* Spectrum List */

       /* Acquition */

            /* AcquisitionParameterSet */
            Acquisition1DType.AcquisitionParameterSet acqparam = 
                      (Acquisition1DType.AcquisitionParameterSet) objFactory.createAcquisition1DTypeAcquisitionParameterSet();
            acqparam.setNumberOfScans(new BigInteger("64"));

            ValueWithUnitType  SweepWidth = (ValueWithUnitType) objFactory.createValueWithUnitType();            
            SweepWidth.setValue("12.01532577");
            SweepWidth.setUnitCvRef(cvUO);
            SweepWidth.setUnitAccession("UO_0000169");
            SweepWidth.setUnitName("parts per million");
            
            ValueWithUnitType  IrradiationFrequency = (ValueWithUnitType) objFactory.createValueWithUnitType();
            IrradiationFrequency.setValue("500162500.8");
            IrradiationFrequency.setUnitCvRef(cvUO);
            IrradiationFrequency.setUnitAccession("UO_0000106");
            IrradiationFrequency.setUnitName("Hertz");

            ValueWithUnitType  gammaB1PulseFieldStrength = (ValueWithUnitType) objFactory.createValueWithUnitType();
            gammaB1PulseFieldStrength.setValue("500160000.0");
            gammaB1PulseFieldStrength.setUnitCvRef(cvUO);
            gammaB1PulseFieldStrength.setUnitAccession("UO_0000169");
            gammaB1PulseFieldStrength.setUnitName("Hertz");
            
           /* DirectDimensionParameterSet */
            AcquisitionDimensionParameterSetType acqdimparam = 
                     (AcquisitionDimensionParameterSetType) objFactory.createAcquisitionDimensionParameterSetType();
            acqdimparam.setNumberOfDataPoints(new BigInteger("32768"));
            acqdimparam.setAcquisitionNucleus("1H");
            acqdimparam.setSweepWidth(SweepWidth);
            acqdimparam.setIrradiationFrequency(IrradiationFrequency);
            acqdimparam.setGammaB1PulseFieldStrength(gammaB1PulseFieldStrength);
            acqparam.setDirectDimensionParameterSet(acqdimparam);

           /* Acquisition1D */
            Acquisition1DType acq1Dtype = (Acquisition1DType) objFactory.createAcquisition1DType();
            acq1Dtype.setAcquisitionParameterSet(acqparam);

            AcquisitionType acqtype = (AcquisitionType) objFactory.createAcquisitionType();
            acqtype.setAcquisition1D(acq1Dtype);

            nmrMLtype.setAcquisition(acqtype);

       /* Generate XML */
            JAXBElement<NmrMLType> nmrML = (JAXBElement<NmrMLType>) objFactory.createNmrML(nmrMLtype);

            // create a JAXBContext capable of handling classes generated into the org.po package
            JAXBContext jc = JAXBContext.newInstance( "org.nmrml.schema" );

            // create a Marshaller and marshal to a file
            Marshaller m = jc.createMarshaller();
            m.setProperty( Marshaller.JAXB_FORMATTED_OUTPUT, new Boolean(true) );
            m.marshal( nmrML, System.out );
System.out.println("OK");
            
        } catch( JAXBException je ) {
            je.printStackTrace();
        }
    }
}
