//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:31:51 PM GMT 
//


package org.nmrml.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MultipletType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultipletType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="atoms" type="{http://nmrml.org/schema}AtomRefsType"/>
 *         &lt;element name="multiplicity" type="{http://nmrml.org/schema}CVTermType"/>
 *         &lt;element name="peakList" type="{http://nmrml.org/schema}PeakListType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="center" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultipletType", propOrder = {
    "atoms",
    "multiplicity",
    "peakList"
})
public class MultipletType {

    @XmlElement(required = true)
    protected AtomRefsType atoms;
    @XmlElement(required = true)
    protected CVTermType multiplicity;
    protected PeakListType peakList;
    @XmlAttribute(name = "center", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String center;

    /**
     * Gets the value of the atoms property.
     * 
     * @return
     *     possible object is
     *     {@link AtomRefsType }
     *     
     */
    public AtomRefsType getAtoms() {
        return atoms;
    }

    /**
     * Sets the value of the atoms property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtomRefsType }
     *     
     */
    public void setAtoms(AtomRefsType value) {
        this.atoms = value;
    }

    /**
     * Gets the value of the multiplicity property.
     * 
     * @return
     *     possible object is
     *     {@link CVTermType }
     *     
     */
    public CVTermType getMultiplicity() {
        return multiplicity;
    }

    /**
     * Sets the value of the multiplicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link CVTermType }
     *     
     */
    public void setMultiplicity(CVTermType value) {
        this.multiplicity = value;
    }

    /**
     * Gets the value of the peakList property.
     * 
     * @return
     *     possible object is
     *     {@link PeakListType }
     *     
     */
    public PeakListType getPeakList() {
        return peakList;
    }

    /**
     * Sets the value of the peakList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeakListType }
     *     
     */
    public void setPeakList(PeakListType value) {
        this.peakList = value;
    }

    /**
     * Gets the value of the center property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCenter() {
        return center;
    }

    /**
     * Sets the value of the center property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCenter(String value) {
        this.center = value;
    }

}
