//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:31:51 PM GMT 
//


package org.nmrml.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.nmrml.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NmrML_QNAME = new QName("http://nmrml.org/schema", "nmrML");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.nmrml.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SampleType }
     * 
     */
    public SampleType createSampleType() {
        return new SampleType();
    }

    /**
     * Create an instance of {@link SpectrumType }
     * 
     */
    public SpectrumType createSpectrumType() {
        return new SpectrumType();
    }

    /**
     * Create an instance of {@link FirstDimensionProcessingParameterSetType }
     * 
     */
    public FirstDimensionProcessingParameterSetType createFirstDimensionProcessingParameterSetType() {
        return new FirstDimensionProcessingParameterSetType();
    }

    /**
     * Create an instance of {@link AcquisitionParameterSetMultiDType }
     * 
     */
    public AcquisitionParameterSetMultiDType createAcquisitionParameterSetMultiDType() {
        return new AcquisitionParameterSetMultiDType();
    }

    /**
     * Create an instance of {@link NmrMLType }
     * 
     */
    public NmrMLType createNmrMLType() {
        return new NmrMLType();
    }

    /**
     * Create an instance of {@link BondType }
     * 
     */
    public BondType createBondType() {
        return new BondType();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link SpectrumListType }
     * 
     */
    public SpectrumListType createSpectrumListType() {
        return new SpectrumListType();
    }

    /**
     * Create an instance of {@link QuantifiedCompoundType }
     * 
     */
    public QuantifiedCompoundType createQuantifiedCompoundType() {
        return new QuantifiedCompoundType();
    }

    /**
     * Create an instance of {@link SoftwareType }
     * 
     */
    public SoftwareType createSoftwareType() {
        return new SoftwareType();
    }

    /**
     * Create an instance of {@link CVParamWithUnitType }
     * 
     */
    public CVParamWithUnitType createCVParamWithUnitType() {
        return new CVParamWithUnitType();
    }

    /**
     * Create an instance of {@link AcquisitionMultiDType }
     * 
     */
    public AcquisitionMultiDType createAcquisitionMultiDType() {
        return new AcquisitionMultiDType();
    }

    /**
     * Create an instance of {@link UserParamType }
     * 
     */
    public UserParamType createUserParamType() {
        return new UserParamType();
    }

    /**
     * Create an instance of {@link ContactListType }
     * 
     */
    public ContactListType createContactListType() {
        return new ContactListType();
    }

    /**
     * Create an instance of {@link SourceFileType }
     * 
     */
    public SourceFileType createSourceFileType() {
        return new SourceFileType();
    }

    /**
     * Create an instance of {@link AtomRefsType }
     * 
     */
    public AtomRefsType createAtomRefsType() {
        return new AtomRefsType();
    }

    /**
     * Create an instance of {@link PeakType }
     * 
     */
    public PeakType createPeakType() {
        return new PeakType();
    }

    /**
     * Create an instance of {@link ClusterListType }
     * 
     */
    public ClusterListType createClusterListType() {
        return new ClusterListType();
    }

    /**
     * Create an instance of {@link CompoundIdentifierListType }
     * 
     */
    public CompoundIdentifierListType createCompoundIdentifierListType() {
        return new CompoundIdentifierListType();
    }

    /**
     * Create an instance of {@link InstrumentConfigurationListType }
     * 
     */
    public InstrumentConfigurationListType createInstrumentConfigurationListType() {
        return new InstrumentConfigurationListType();
    }

    /**
     * Create an instance of {@link PulseSequenceType }
     * 
     */
    public PulseSequenceType createPulseSequenceType() {
        return new PulseSequenceType();
    }

    /**
     * Create an instance of {@link SampleListType }
     * 
     */
    public SampleListType createSampleListType() {
        return new SampleListType();
    }

    /**
     * Create an instance of {@link PeakListType }
     * 
     */
    public PeakListType createPeakListType() {
        return new PeakListType();
    }

    /**
     * Create an instance of {@link ValueWithUnitType }
     * 
     */
    public ValueWithUnitType createValueWithUnitType() {
        return new ValueWithUnitType();
    }

    /**
     * Create an instance of {@link SpectrumAnnotationListType }
     * 
     */
    public SpectrumAnnotationListType createSpectrumAnnotationListType() {
        return new SpectrumAnnotationListType();
    }

    /**
     * Create an instance of {@link BinaryDataArrayType }
     * 
     */
    public BinaryDataArrayType createBinaryDataArrayType() {
        return new BinaryDataArrayType();
    }

    /**
     * Create an instance of {@link SoftwareRefListType }
     * 
     */
    public SoftwareRefListType createSoftwareRefListType() {
        return new SoftwareRefListType();
    }

    /**
     * Create an instance of {@link QuantificationAnnotationType }
     * 
     */
    public QuantificationAnnotationType createQuantificationAnnotationType() {
        return new QuantificationAnnotationType();
    }

    /**
     * Create an instance of {@link AcquisitionType }
     * 
     */
    public AcquisitionType createAcquisitionType() {
        return new AcquisitionType();
    }

    /**
     * Create an instance of {@link BondListType }
     * 
     */
    public BondListType createBondListType() {
        return new BondListType();
    }

    /**
     * Create an instance of {@link SpectrumRefListType }
     * 
     */
    public SpectrumRefListType createSpectrumRefListType() {
        return new SpectrumRefListType();
    }

    /**
     * Create an instance of {@link ContactRefListType }
     * 
     */
    public ContactRefListType createContactRefListType() {
        return new ContactRefListType();
    }

    /**
     * Create an instance of {@link AcquisitionParameterSetType }
     * 
     */
    public AcquisitionParameterSetType createAcquisitionParameterSetType() {
        return new AcquisitionParameterSetType();
    }

    /**
     * Create an instance of {@link InstrumentConfigurationType }
     * 
     */
    public InstrumentConfigurationType createInstrumentConfigurationType() {
        return new InstrumentConfigurationType();
    }

    /**
     * Create an instance of {@link Acquisition1DType }
     * 
     */
    public Acquisition1DType createAcquisition1DType() {
        return new Acquisition1DType();
    }

    /**
     * Create an instance of {@link SpectralProcessingParameterSet2DType }
     * 
     */
    public SpectralProcessingParameterSet2DType createSpectralProcessingParameterSet2DType() {
        return new SpectralProcessingParameterSet2DType();
    }

    /**
     * Create an instance of {@link SpectralProcessingParameterSetType }
     * 
     */
    public SpectralProcessingParameterSetType createSpectralProcessingParameterSetType() {
        return new SpectralProcessingParameterSetType();
    }

    /**
     * Create an instance of {@link InChiStringType }
     * 
     */
    public InChiStringType createInChiStringType() {
        return new InChiStringType();
    }

    /**
     * Create an instance of {@link AdditionalSoluteListType }
     * 
     */
    public AdditionalSoluteListType createAdditionalSoluteListType() {
        return new AdditionalSoluteListType();
    }

    /**
     * Create an instance of {@link AxisWithUnitType }
     * 
     */
    public AxisWithUnitType createAxisWithUnitType() {
        return new AxisWithUnitType();
    }

    /**
     * Create an instance of {@link CVTermType }
     * 
     */
    public CVTermType createCVTermType() {
        return new CVTermType();
    }

    /**
     * Create an instance of {@link AtomAssingmentAnnotationType }
     * 
     */
    public AtomAssingmentAnnotationType createAtomAssingmentAnnotationType() {
        return new AtomAssingmentAnnotationType();
    }

    /**
     * Create an instance of {@link Spectrum1DType }
     * 
     */
    public Spectrum1DType createSpectrum1DType() {
        return new Spectrum1DType();
    }

    /**
     * Create an instance of {@link SourceFileRefType }
     * 
     */
    public SourceFileRefType createSourceFileRefType() {
        return new SourceFileRefType();
    }

    /**
     * Create an instance of {@link AcquisitionDimensionParameterSetType }
     * 
     */
    public AcquisitionDimensionParameterSetType createAcquisitionDimensionParameterSetType() {
        return new AcquisitionDimensionParameterSetType();
    }

    /**
     * Create an instance of {@link SoluteType }
     * 
     */
    public SoluteType createSoluteType() {
        return new SoluteType();
    }

    /**
     * Create an instance of {@link CVListType }
     * 
     */
    public CVListType createCVListType() {
        return new CVListType();
    }

    /**
     * Create an instance of {@link ReferenceableParamGroupListType }
     * 
     */
    public ReferenceableParamGroupListType createReferenceableParamGroupListType() {
        return new ReferenceableParamGroupListType();
    }

    /**
     * Create an instance of {@link AtomListType }
     * 
     */
    public AtomListType createAtomListType() {
        return new AtomListType();
    }

    /**
     * Create an instance of {@link ContactRefType }
     * 
     */
    public ContactRefType createContactRefType() {
        return new ContactRefType();
    }

    /**
     * Create an instance of {@link AcquisitionParameterSet1DType }
     * 
     */
    public AcquisitionParameterSet1DType createAcquisitionParameterSet1DType() {
        return new AcquisitionParameterSet1DType();
    }

    /**
     * Create an instance of {@link ReferenceableParamGroupType }
     * 
     */
    public ReferenceableParamGroupType createReferenceableParamGroupType() {
        return new ReferenceableParamGroupType();
    }

    /**
     * Create an instance of {@link AtomAssignmentListType }
     * 
     */
    public AtomAssignmentListType createAtomAssignmentListType() {
        return new AtomAssignmentListType();
    }

    /**
     * Create an instance of {@link SpectrumRefType }
     * 
     */
    public SpectrumRefType createSpectrumRefType() {
        return new SpectrumRefType();
    }

    /**
     * Create an instance of {@link AtomType }
     * 
     */
    public AtomType createAtomType() {
        return new AtomType();
    }

    /**
     * Create an instance of {@link SourceFileListType }
     * 
     */
    public SourceFileListType createSourceFileListType() {
        return new SourceFileListType();
    }

    /**
     * Create an instance of {@link CVParamType }
     * 
     */
    public CVParamType createCVParamType() {
        return new CVParamType();
    }

    /**
     * Create an instance of {@link ChemicalCompoundType }
     * 
     */
    public ChemicalCompoundType createChemicalCompoundType() {
        return new ChemicalCompoundType();
    }

    /**
     * Create an instance of {@link FileDescriptionType }
     * 
     */
    public FileDescriptionType createFileDescriptionType() {
        return new FileDescriptionType();
    }

    /**
     * Create an instance of {@link ParamGroupType }
     * 
     */
    public ParamGroupType createParamGroupType() {
        return new ParamGroupType();
    }

    /**
     * Create an instance of {@link MultipletType }
     * 
     */
    public MultipletType createMultipletType() {
        return new MultipletType();
    }

    /**
     * Create an instance of {@link CompoundDatabaseIdentifierType }
     * 
     */
    public CompoundDatabaseIdentifierType createCompoundDatabaseIdentifierType() {
        return new CompoundDatabaseIdentifierType();
    }

    /**
     * Create an instance of {@link ClusterType }
     * 
     */
    public ClusterType createClusterType() {
        return new ClusterType();
    }

    /**
     * Create an instance of {@link CompoundStructureType }
     * 
     */
    public CompoundStructureType createCompoundStructureType() {
        return new CompoundStructureType();
    }

    /**
     * Create an instance of {@link SpectralProjectionParameterSetType }
     * 
     */
    public SpectralProjectionParameterSetType createSpectralProjectionParameterSetType() {
        return new SpectralProjectionParameterSetType();
    }

    /**
     * Create an instance of {@link SourceFileRefListType }
     * 
     */
    public SourceFileRefListType createSourceFileRefListType() {
        return new SourceFileRefListType();
    }

    /**
     * Create an instance of {@link TemperatureType }
     * 
     */
    public TemperatureType createTemperatureType() {
        return new TemperatureType();
    }

    /**
     * Create an instance of {@link ReferenceableParamGroupRefType }
     * 
     */
    public ReferenceableParamGroupRefType createReferenceableParamGroupRefType() {
        return new ReferenceableParamGroupRefType();
    }

    /**
     * Create an instance of {@link SoftwareRefType }
     * 
     */
    public SoftwareRefType createSoftwareRefType() {
        return new SoftwareRefType();
    }

    /**
     * Create an instance of {@link HigherDimensionProcessingParameterSetType }
     * 
     */
    public HigherDimensionProcessingParameterSetType createHigherDimensionProcessingParameterSetType() {
        return new HigherDimensionProcessingParameterSetType();
    }

    /**
     * Create an instance of {@link CVType }
     * 
     */
    public CVType createCVType() {
        return new CVType();
    }

    /**
     * Create an instance of {@link SoftwareListType }
     * 
     */
    public SoftwareListType createSoftwareListType() {
        return new SoftwareListType();
    }

    /**
     * Create an instance of {@link Projected3DProcessingParamaterSetType }
     * 
     */
    public Projected3DProcessingParamaterSetType createProjected3DProcessingParamaterSetType() {
        return new Projected3DProcessingParamaterSetType();
    }

    /**
     * Create an instance of {@link SpectrumMultiDType }
     * 
     */
    public SpectrumMultiDType createSpectrumMultiDType() {
        return new SpectrumMultiDType();
    }

    /**
     * Create an instance of {@link QuantifiedCompoundListType }
     * 
     */
    public QuantifiedCompoundListType createQuantifiedCompoundListType() {
        return new QuantifiedCompoundListType();
    }

    /**
     * Create an instance of {@link AcquisitionIndirectDimensionParameterSetType }
     * 
     */
    public AcquisitionIndirectDimensionParameterSetType createAcquisitionIndirectDimensionParameterSetType() {
        return new AcquisitionIndirectDimensionParameterSetType();
    }

    /**
     * Create an instance of {@link SampleType.FieldFrequencyLock }
     * 
     */
    public SampleType.FieldFrequencyLock createSampleTypeFieldFrequencyLock() {
        return new SampleType.FieldFrequencyLock();
    }

    /**
     * Create an instance of {@link SampleType.ConcentrationStandard }
     * 
     */
    public SampleType.ConcentrationStandard createSampleTypeConcentrationStandard() {
        return new SampleType.ConcentrationStandard();
    }

    /**
     * Create an instance of {@link SpectrumType.ProcessingParameterSet }
     * 
     */
    public SpectrumType.ProcessingParameterSet createSpectrumTypeProcessingParameterSet() {
        return new SpectrumType.ProcessingParameterSet();
    }

    /**
     * Create an instance of {@link FirstDimensionProcessingParameterSetType.WindowFunction }
     * 
     */
    public FirstDimensionProcessingParameterSetType.WindowFunction createFirstDimensionProcessingParameterSetTypeWindowFunction() {
        return new FirstDimensionProcessingParameterSetType.WindowFunction();
    }

    /**
     * Create an instance of {@link AcquisitionParameterSetMultiDType.HadamardParameterSet }
     * 
     */
    public AcquisitionParameterSetMultiDType.HadamardParameterSet createAcquisitionParameterSetMultiDTypeHadamardParameterSet() {
        return new AcquisitionParameterSetMultiDType.HadamardParameterSet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NmrMLType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nmrml.org/schema", name = "nmrML")
    public JAXBElement<NmrMLType> createNmrML(NmrMLType value) {
        return new JAXBElement<NmrMLType>(_NmrML_QNAME, NmrMLType.class, null, value);
    }

}
