//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:31:51 PM GMT 
//


package org.nmrml.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SampleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SampleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originalBiologicalSamplepH" type="{http://nmrml.org/schema}PhType" minOccurs="0"/>
 *         &lt;element name="postBufferpH" type="{http://nmrml.org/schema}PhType" minOccurs="0"/>
 *         &lt;element name="buffer" type="{http://nmrml.org/schema}CVTermType" minOccurs="0"/>
 *         &lt;element name="fieldFrequencyLock">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="fieldFrequencyLockName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="chemicalShiftStandard" type="{http://nmrml.org/schema}CVParamType"/>
 *         &lt;element name="solventType" type="{http://nmrml.org/schema}CVParamWithUnitType" maxOccurs="unbounded"/>
 *         &lt;element name="additionalSoluteList" type="{http://nmrml.org/schema}AdditionalSoluteListType"/>
 *         &lt;element name="concentrationStandard" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="type" type="{http://nmrml.org/schema}CVTermType"/>
 *                   &lt;element name="concentrationInSample" type="{http://nmrml.org/schema}ValueWithUnitType"/>
 *                   &lt;element name="name" type="{http://nmrml.org/schema}CVTermType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="originalBiologicalSampleReference" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SampleType", propOrder = {
    "originalBiologicalSamplepH",
    "postBufferpH",
    "buffer",
    "fieldFrequencyLock",
    "chemicalShiftStandard",
    "solventType",
    "additionalSoluteList",
    "concentrationStandard"
})
public class SampleType {

    protected Double originalBiologicalSamplepH;
    protected Double postBufferpH;
    protected CVTermType buffer;
    @XmlElement(required = true)
    protected SampleType.FieldFrequencyLock fieldFrequencyLock;
    @XmlElement(required = true)
    protected CVParamType chemicalShiftStandard;
    @XmlElement(required = true)
    protected List<CVParamWithUnitType> solventType;
    @XmlElement(required = true)
    protected AdditionalSoluteListType additionalSoluteList;
    protected SampleType.ConcentrationStandard concentrationStandard;
    @XmlAttribute(name = "originalBiologicalSampleReference", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String originalBiologicalSampleReference;

    /**
     * Gets the value of the originalBiologicalSamplepH property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOriginalBiologicalSamplepH() {
        return originalBiologicalSamplepH;
    }

    /**
     * Sets the value of the originalBiologicalSamplepH property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOriginalBiologicalSamplepH(Double value) {
        this.originalBiologicalSamplepH = value;
    }

    /**
     * Gets the value of the postBufferpH property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPostBufferpH() {
        return postBufferpH;
    }

    /**
     * Sets the value of the postBufferpH property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPostBufferpH(Double value) {
        this.postBufferpH = value;
    }

    /**
     * Gets the value of the buffer property.
     * 
     * @return
     *     possible object is
     *     {@link CVTermType }
     *     
     */
    public CVTermType getBuffer() {
        return buffer;
    }

    /**
     * Sets the value of the buffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CVTermType }
     *     
     */
    public void setBuffer(CVTermType value) {
        this.buffer = value;
    }

    /**
     * Gets the value of the fieldFrequencyLock property.
     * 
     * @return
     *     possible object is
     *     {@link SampleType.FieldFrequencyLock }
     *     
     */
    public SampleType.FieldFrequencyLock getFieldFrequencyLock() {
        return fieldFrequencyLock;
    }

    /**
     * Sets the value of the fieldFrequencyLock property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampleType.FieldFrequencyLock }
     *     
     */
    public void setFieldFrequencyLock(SampleType.FieldFrequencyLock value) {
        this.fieldFrequencyLock = value;
    }

    /**
     * Gets the value of the chemicalShiftStandard property.
     * 
     * @return
     *     possible object is
     *     {@link CVParamType }
     *     
     */
    public CVParamType getChemicalShiftStandard() {
        return chemicalShiftStandard;
    }

    /**
     * Sets the value of the chemicalShiftStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link CVParamType }
     *     
     */
    public void setChemicalShiftStandard(CVParamType value) {
        this.chemicalShiftStandard = value;
    }

    /**
     * Gets the value of the solventType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the solventType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSolventType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CVParamWithUnitType }
     * 
     * 
     */
    public List<CVParamWithUnitType> getSolventType() {
        if (solventType == null) {
            solventType = new ArrayList<CVParamWithUnitType>();
        }
        return this.solventType;
    }

    /**
     * Gets the value of the additionalSoluteList property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalSoluteListType }
     *     
     */
    public AdditionalSoluteListType getAdditionalSoluteList() {
        return additionalSoluteList;
    }

    /**
     * Sets the value of the additionalSoluteList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalSoluteListType }
     *     
     */
    public void setAdditionalSoluteList(AdditionalSoluteListType value) {
        this.additionalSoluteList = value;
    }

    /**
     * Gets the value of the concentrationStandard property.
     * 
     * @return
     *     possible object is
     *     {@link SampleType.ConcentrationStandard }
     *     
     */
    public SampleType.ConcentrationStandard getConcentrationStandard() {
        return concentrationStandard;
    }

    /**
     * Sets the value of the concentrationStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampleType.ConcentrationStandard }
     *     
     */
    public void setConcentrationStandard(SampleType.ConcentrationStandard value) {
        this.concentrationStandard = value;
    }

    /**
     * Gets the value of the originalBiologicalSampleReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalBiologicalSampleReference() {
        return originalBiologicalSampleReference;
    }

    /**
     * Sets the value of the originalBiologicalSampleReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalBiologicalSampleReference(String value) {
        this.originalBiologicalSampleReference = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="type" type="{http://nmrml.org/schema}CVTermType"/>
     *         &lt;element name="concentrationInSample" type="{http://nmrml.org/schema}ValueWithUnitType"/>
     *         &lt;element name="name" type="{http://nmrml.org/schema}CVTermType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "concentrationInSample",
        "name"
    })
    public static class ConcentrationStandard {

        @XmlElement(required = true)
        protected CVTermType type;
        @XmlElement(required = true)
        protected ValueWithUnitType concentrationInSample;
        @XmlElement(required = true)
        protected CVTermType name;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link CVTermType }
         *     
         */
        public CVTermType getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link CVTermType }
         *     
         */
        public void setType(CVTermType value) {
            this.type = value;
        }

        /**
         * Gets the value of the concentrationInSample property.
         * 
         * @return
         *     possible object is
         *     {@link ValueWithUnitType }
         *     
         */
        public ValueWithUnitType getConcentrationInSample() {
            return concentrationInSample;
        }

        /**
         * Sets the value of the concentrationInSample property.
         * 
         * @param value
         *     allowed object is
         *     {@link ValueWithUnitType }
         *     
         */
        public void setConcentrationInSample(ValueWithUnitType value) {
            this.concentrationInSample = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link CVTermType }
         *     
         */
        public CVTermType getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link CVTermType }
         *     
         */
        public void setName(CVTermType value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="fieldFrequencyLockName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FieldFrequencyLock {

        @XmlAttribute(name = "fieldFrequencyLockName", required = true)
        protected String fieldFrequencyLockName;

        /**
         * Gets the value of the fieldFrequencyLockName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFieldFrequencyLockName() {
            return fieldFrequencyLockName;
        }

        /**
         * Sets the value of the fieldFrequencyLockName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFieldFrequencyLockName(String value) {
            this.fieldFrequencyLockName = value;
        }

    }

}
