//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:31:51 PM GMT 
//


package org.nmrml.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A spectrum that is the result of processing the acquisition and a
 *         description of the process used to create it.
 * 
 * <p>Java class for SpectrumType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpectrumType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="processingSoftwareRefList" type="{http://nmrml.org/schema}SoftwareRefListType" minOccurs="0"/>
 *         &lt;element name="spectrumDataArray" type="{http://nmrml.org/schema}BinaryDataArrayType"/>
 *         &lt;element name="xAxis" type="{http://nmrml.org/schema}AxisWithUnitType"/>
 *         &lt;element name="processingParameterSet" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="postAcquisitionSolventSuppressionMethod" type="{http://nmrml.org/schema}CVTermType" minOccurs="0"/>
 *                   &lt;element name="calibrationCompound" type="{http://nmrml.org/schema}CVTermType" minOccurs="0"/>
 *                   &lt;element name="dataTransformationMethod" type="{http://nmrml.org/schema}CVTermType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="numberOfDataPoints" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpectrumType", propOrder = {
    "processingSoftwareRefList",
    "spectrumDataArray",
    "xAxis",
    "processingParameterSet"
})
@XmlSeeAlso({
    Spectrum1DType.class,
    SpectrumMultiDType.class
})
public class SpectrumType {

    protected SoftwareRefListType processingSoftwareRefList;
    @XmlElement(required = true)
    protected BinaryDataArrayType spectrumDataArray;
    @XmlElement(required = true)
    protected AxisWithUnitType xAxis;
    protected SpectrumType.ProcessingParameterSet processingParameterSet;
    @XmlAttribute(name = "numberOfDataPoints", required = true)
    protected BigInteger numberOfDataPoints;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;

    /**
     * Gets the value of the processingSoftwareRefList property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareRefListType }
     *     
     */
    public SoftwareRefListType getProcessingSoftwareRefList() {
        return processingSoftwareRefList;
    }

    /**
     * Sets the value of the processingSoftwareRefList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareRefListType }
     *     
     */
    public void setProcessingSoftwareRefList(SoftwareRefListType value) {
        this.processingSoftwareRefList = value;
    }

    /**
     * Gets the value of the spectrumDataArray property.
     * 
     * @return
     *     possible object is
     *     {@link BinaryDataArrayType }
     *     
     */
    public BinaryDataArrayType getSpectrumDataArray() {
        return spectrumDataArray;
    }

    /**
     * Sets the value of the spectrumDataArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinaryDataArrayType }
     *     
     */
    public void setSpectrumDataArray(BinaryDataArrayType value) {
        this.spectrumDataArray = value;
    }

    /**
     * Gets the value of the xAxis property.
     * 
     * @return
     *     possible object is
     *     {@link AxisWithUnitType }
     *     
     */
    public AxisWithUnitType getXAxis() {
        return xAxis;
    }

    /**
     * Sets the value of the xAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link AxisWithUnitType }
     *     
     */
    public void setXAxis(AxisWithUnitType value) {
        this.xAxis = value;
    }

    /**
     * Gets the value of the processingParameterSet property.
     * 
     * @return
     *     possible object is
     *     {@link SpectrumType.ProcessingParameterSet }
     *     
     */
    public SpectrumType.ProcessingParameterSet getProcessingParameterSet() {
        return processingParameterSet;
    }

    /**
     * Sets the value of the processingParameterSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpectrumType.ProcessingParameterSet }
     *     
     */
    public void setProcessingParameterSet(SpectrumType.ProcessingParameterSet value) {
        this.processingParameterSet = value;
    }

    /**
     * Gets the value of the numberOfDataPoints property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfDataPoints() {
        return numberOfDataPoints;
    }

    /**
     * Sets the value of the numberOfDataPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfDataPoints(BigInteger value) {
        this.numberOfDataPoints = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="postAcquisitionSolventSuppressionMethod" type="{http://nmrml.org/schema}CVTermType" minOccurs="0"/>
     *         &lt;element name="calibrationCompound" type="{http://nmrml.org/schema}CVTermType" minOccurs="0"/>
     *         &lt;element name="dataTransformationMethod" type="{http://nmrml.org/schema}CVTermType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "postAcquisitionSolventSuppressionMethod",
        "calibrationCompound",
        "dataTransformationMethod"
    })
    public static class ProcessingParameterSet {

        protected CVTermType postAcquisitionSolventSuppressionMethod;
        protected CVTermType calibrationCompound;
        protected CVTermType dataTransformationMethod;

        /**
         * Gets the value of the postAcquisitionSolventSuppressionMethod property.
         * 
         * @return
         *     possible object is
         *     {@link CVTermType }
         *     
         */
        public CVTermType getPostAcquisitionSolventSuppressionMethod() {
            return postAcquisitionSolventSuppressionMethod;
        }

        /**
         * Sets the value of the postAcquisitionSolventSuppressionMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link CVTermType }
         *     
         */
        public void setPostAcquisitionSolventSuppressionMethod(CVTermType value) {
            this.postAcquisitionSolventSuppressionMethod = value;
        }

        /**
         * Gets the value of the calibrationCompound property.
         * 
         * @return
         *     possible object is
         *     {@link CVTermType }
         *     
         */
        public CVTermType getCalibrationCompound() {
            return calibrationCompound;
        }

        /**
         * Sets the value of the calibrationCompound property.
         * 
         * @param value
         *     allowed object is
         *     {@link CVTermType }
         *     
         */
        public void setCalibrationCompound(CVTermType value) {
            this.calibrationCompound = value;
        }

        /**
         * Gets the value of the dataTransformationMethod property.
         * 
         * @return
         *     possible object is
         *     {@link CVTermType }
         *     
         */
        public CVTermType getDataTransformationMethod() {
            return dataTransformationMethod;
        }

        /**
         * Sets the value of the dataTransformationMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link CVTermType }
         *     
         */
        public void setDataTransformationMethod(CVTermType value) {
            this.dataTransformationMethod = value;
        }

    }

}
