/*
 * $Id: Converter.java,v 1.0.alpha Feb 2014 (C) INRA - DJ $
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.nmrml.converter;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.ByteOrder;
import java.nio.file.Paths;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.GnuParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.MissingArgumentException;
import org.apache.commons.cli.MissingOptionException;
import org.apache.commons.cli.OptionBuilder;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;
import org.apache.commons.cli.PosixParser;

import java.util.*;
import java.lang.*;

import org.nmrml.parser.*;
import org.nmrml.parser.bruker.*;
import org.nmrml.parser.varian.*;

import org.nmrml.cv.*;
import org.nmrml.converter.*;

// create a nmrML file based on a java object tree generated by the JAXB XJC Tool (JDK 7 and above).
public class nmrMLcreate {

    private static final String Version = "1.1b";

    private enum Vendor_Type { bruker, varian; }

    public nmrMLcreate( ) { }

    public void launch( String[] args ) {

        Acqu2nmrML nmrmlObj = new Acqu2nmrML();

        /* Containers of Acquisition/Processing Parameters  */
        String Vendor = "bruker";

        Options options = new Options();
        options.addOption("h", "help", false, "prints the help content");
        options.addOption("v", "version", false, "prints the version");
        options.addOption("b","binary-data",false,"include fid binary data");
        options.addOption("z","compress",false,"compress binary data");
        options.addOption(OptionBuilder
           .withArgName("directory")
           .hasArg()
           .isRequired()
           .withDescription("input directory")
           .withLongOpt("inputdir")
           .create("i"));
        options.addOption(OptionBuilder
           .withArgName("config.properties")
           .hasArg()
           .withDescription("properties configuration file")
           .withLongOpt("prop")
           .create());
        options.addOption(OptionBuilder
           .withArgName("vendor")
           .hasArg()
           .withDescription("vendor type")
           .withLongOpt("type")
           .create("t"));
        options.addOption(OptionBuilder
           .withArgName("file")
           .hasArg()
           .withDescription("output file")
           .withLongOpt("outputfile")
           .create("o"));

        try {

           CommandLineParser parser = new GnuParser();
           CommandLine cmd = parser.parse(options, args);
           String inputFolder = cmd.getOptionValue("i");
           inputFolder = ( inputFolder.lastIndexOf("/") == inputFolder.length() ) ? inputFolder : inputFolder.concat("/");
           nmrmlObj.setInputFolder(inputFolder);

        /* Properties object */
           Properties prop = new Properties();
           if (cmd.hasOption("prop")) {
           String conffile = cmd.getOptionValue("prop");
               prop.load(new FileInputStream(conffile));
           } else {
               prop.load(nmrMLpipe.class.getClassLoader().getResourceAsStream("resources/config.properties"));
           }
           String onto_ini = prop.getProperty("onto_ini_file");
           nmrmlObj.setSchemaLocation( prop.getProperty("schemaLocation") );

           CVLoader cvLoader = (new File(onto_ini)).isFile() ?
                          new CVLoader(new FileInputStream(onto_ini)) : 
                          new CVLoader(nmrMLpipe.class.getClassLoader().getResourceAsStream("resources/onto.ini"));
           nmrmlObj.setCVLoader(cvLoader);

           if(cmd.hasOption("t")) {
                 Vendor = cmd.getOptionValue("t").toLowerCase();
           }
           String vendor_ini = prop.getProperty(Vendor);
           Vendor_Type vendor_type = Vendor_Type.valueOf(Vendor);

       /* Vendor terms file */
           SpectrometerMapper vendorMapper = (new File(vendor_ini)).isFile() ? 
                         new SpectrometerMapper(vendor_ini) : vendor_type == Vendor_Type.bruker ? 
                         new SpectrometerMapper(nmrMLpipe.class.getClassLoader().getResourceAsStream("resources/bruker.ini")) :
                         new SpectrometerMapper(nmrMLpipe.class.getClassLoader().getResourceAsStream("resources/varian.ini")) ;

           nmrmlObj.setVendorMapper(vendorMapper);

       /* Get Acquisition Parameters depending on the vendor type */
           File dataFolder = new File(inputFolder);
           String acqFstr = dataFolder.getAbsolutePath() + "/" + vendorMapper.getTerm("FILES", "ACQUISITION_FILE");
           File acquFile = new File(acqFstr);
           if(acquFile.isFile() && acquFile.canRead()) {
               switch (vendor_type) {
                  case bruker:
                       BrukerAcquReader brukerAcqObj = new BrukerAcquReader(acquFile);
                       nmrmlObj.setAcqu(brukerAcqObj.read());
                       break;
                  case varian:
                       VarianAcquReader varianAcqObj = new VarianAcquReader(acquFile);
                       Acqu acq = varianAcqObj.read();
                       acq.setSoftware(vendorMapper.getTerm("SOFTWARE", "SOFTWARE"));
                       acq.setSoftVersion(vendorMapper.getTerm("SOFTWARE", "VERSION"));
                       switch (Integer.parseInt(vendorMapper.getTerm("BYTORDA", "ENDIAN"))){
                            case 0 :
                                acq.setByteOrder(ByteOrder.LITTLE_ENDIAN);
                                break;
                            case 1 :
                                acq.setByteOrder(ByteOrder.BIG_ENDIAN);
                                break;
                            default:
                                break;
                       }
                       acq.setDecoupledNucleus("off");
                       nmrmlObj.setAcqu(acq);
                       break;
               }
           }
           else {
               System.err.println("ACQUISITION_FILE not available or readable: " + acqFstr);
               System.exit(1);
           }

           nmrmlObj.setVendorLabel(Vendor.toUpperCase());
           nmrmlObj.setIfbinarydata(cmd.hasOption("b"));
           nmrmlObj.setCompressed(cmd.hasOption("z"));

           if(cmd.hasOption("o")) {
                nmrmlObj.Convert2nmrML( cmd.getOptionValue("o","output.nmrML") );
           } else {
                nmrmlObj.Convert2nmrML( null );
           }

        } catch(MissingOptionException e){
            boolean help = false;
            boolean version = false;
            try{
              Options helpOptions = new Options();
              helpOptions.addOption("h", "help", false, "prints the help content");
              helpOptions.addOption("v", "version", false, "prints the version");
              CommandLineParser parser = new PosixParser();
              CommandLine line = parser.parse(helpOptions, args);
              if(line.hasOption("h")) help = true;
              if(line.hasOption("v")) version = true;
            } catch(Exception ex){ }
            if(!help && !version) System.err.println(e.getMessage());
            if (help) {
                HelpFormatter formatter = new HelpFormatter();
                formatter.printHelp( "nmrMLcreate" , options );
            }
            if (version) {
                System.out.println("nmrML Create version = " + Version);
            }
            System.exit(1);
        } catch(MissingArgumentException e){
            System.err.println(e.getMessage());
            HelpFormatter formatter = new HelpFormatter();
            formatter.printHelp( "App" , options );
            System.exit(1);
        } catch(ParseException e){
            System.err.println("Error while parsing the command line: "+e.getMessage());
            System.exit(1);
        } catch( Exception e ) {
            e.printStackTrace();
        }

    }
}
